In [1]:
from collections import defaultdict, OrderedDict, deque
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy.stats import norm
from scipy.stats import t

In [5]:
#Dict from str

alphabet_str = 'abcdefghijklmnopqrstuvwxyz'

alphabet_list = [x for x in alphabet_str]    #создаем список из элементов строки
alphabet_dict = dict.fromkeys(alphabet_list, 0) #создаем словарь из вышесозданного списка и передаем в качестве значений 0
alphabet_dict_2 = {char:0 for char in alphabet_str}

print(alphabet_list)
print(alphabet_dict)
print(alphabet_dict_2)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
{'a': 0, 'b': 0, 'c': 0, 'd': 0, 'e': 0, 'f': 0, 'g': 0, 'h': 0, 'i': 0, 'j': 0, 'k': 0, 'l': 0, 'm': 0, 'n': 0, 'o': 0, 'p': 0, 'q': 0, 'r': 0, 's': 0, 't': 0, 'u': 0, 'v': 0, 'w': 0, 'x': 0, 'y': 0, 'z': 0}
{'a': 0, 'b': 0, 'c': 0, 'd': 0, 'e': 0, 'f': 0, 'g': 0, 'h': 0, 'i': 0, 'j': 0, 'k': 0, 'l': 0, 'm': 0, 'n': 0, 'o': 0, 'p': 0, 'q': 0, 'r': 0, 's': 0, 't': 0, 'u': 0, 'v': 0, 'w': 0, 'x': 0, 'y': 0, 'z': 0}


In [6]:
#Sorting dictionarie by value
cuisine = {
    'filipino': 11, 'moroccan': 9, 'irish': 9,
    'mexican': 79, 'italian': 101, 'greek': 15,
    'spanish': 12, 'chinese': 39, 'southern_us': 52,
    'thai': 17, 'jamaican': 6, 'indian': 41,
    'vietnamese': 9, 'korean': 21, 'cajun_creole': 16,
    'russian': 2, 'british': 9, 'brazilian': 3,
    'japanese': 24, 'french': 25
}

cuisine = {k: v for k, v in sorted(cuisine.items(), key=lambda item: item[1])}
cuisine

{'russian': 2,
 'brazilian': 3,
 'jamaican': 6,
 'moroccan': 9,
 'irish': 9,
 'vietnamese': 9,
 'british': 9,
 'filipino': 11,
 'spanish': 12,
 'greek': 15,
 'cajun_creole': 16,
 'thai': 17,
 'korean': 21,
 'japanese': 24,
 'french': 25,
 'chinese': 39,
 'indian': 41,
 'southern_us': 52,
 'mexican': 79,
 'italian': 101}

In [7]:
#Matrix/list of lists unpack

groceries = [['Milk', 'Milk', 'Beer'], ['Chocolate', 'Bread', 'Chips']]
groceries_unpacked = [x for x in groceries for x in x]
print(groceries_unpacked)

matrix = [[1,2,3],[3,4,5],[6,7,8]]
matrix_flatten = [x for x in matrix for x in x]
matrix_flatten

['Milk', 'Milk', 'Beer', 'Chocolate', 'Bread', 'Chips']


[1, 2, 3, 3, 4, 5, 6, 7, 8]

In [8]:
#Ordered dict sorting

ratings = [
    ('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
    ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
    ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)
]

cafes = OrderedDict(sorted(ratings, key=lambda x:x[1]))   #change [1] to [0] for sorting by key
print(cafes)

cafes = OrderedDict(sorted(ratings, key=lambda x:-x[1]))  #in reverse by key
print(cafes)

cafes = OrderedDict(sorted(ratings, key=lambda x:x[1]), reverse= True)   #change [1] to [0] for sorting by key
print(cafes)

cafes = OrderedDict(sorted(ratings, key=lambda x:-x[1]), reverse= True)   #change [1] to [0] for sorting by key
print(cafes)

OrderedDict([('Old York', 3.3), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9), ('CakeTime', 4.1), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('Belissimo', 4.5), ('New Age', 4.6), ('General Foods', 4.8), ('WokToWork', 4.9), ('WokAndRice', 4.9)])
OrderedDict([('WokToWork', 4.9), ('WokAndRice', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old York', 3.3), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3)])
OrderedDict([('Old York', 3.3), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9), ('CakeTime', 4.1), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('Belissimo', 4.5), ('New Age', 4.6), ('General Foods', 4.8), ('WokToWork', 4.9), ('WokAndRice', 4.9), ('reverse', True)])
OrderedDict([('WokToWork', 4.9), ('WokAndRice', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('N

In [9]:
#Ordered dict sorting (specific)

ratings = [
    ('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
    ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
    ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)
]

ratings.sort(key=lambda x: (-x[1], x[0]))  #cортировка по ключу и значению в кортеже

cafes = OrderedDict(ratings)

print(cafes)

OrderedDict([('WokAndRice', 4.9), ('WokToWork', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Old York', 3.3)])


In [10]:
#How to create dict from list of tupples with 2 records in value

tasks = [
    (36871, 'office', False),
    (40690, 'office', False),
    (35364, 'voltage', False),
    (41667, 'voltage', True),
    (33850, 'office', False)
]

tasks_dict = defaultdict(list)
for key, value, state in tasks:
    tasks_dict[key].append(value)
    tasks_dict[key].append(state)

sorted(tasks_dict.items())

[(33850, ['office', False]),
 (35364, ['voltage', False]),
 (36871, ['office', False]),
 (40690, ['office', False]),
 (41667, ['voltage', True])]

In [11]:
#How to put dictionaries into the function as arguments

district_1 = {'flat_1' : 10500, 'flat_2' : 11000}
district_2 = {'flat_3' : 15000}
district_3 = {'flat_4' : 6500, 'flat_5' : 7000, 'flat_6' : 6000}

def mean_price(*district):
    
    district_merged = {}
    
    for item in district:
        district_merged.update(item)
        
    grand_total = sum(district_merged.values())
    flat_numbers = district_merged.__len__() #len(district_merged)
    
    return round(grand_total / flat_numbers)

mean_price(district_3, district_2, district_1)

9333

In [12]:
#Creating default dict via 3rd parameter

tasks = [
    (36871, 'office', False),
    (40690, 'office', False),
    (35364, 'voltage', False),
    (41667, 'voltage', True),
    (33850, 'office', False)
]

def task_manager(tasks):
    
    task_dict = defaultdict(dict)
    
    for value, key, state in tasks:
        if state == True:
            task_dict.setdefault(key, deque()).appendleft(value)  #if State is == True thus the priority is higher
        else:
            task_dict.setdefault(key, deque()).append(value)      #place task after the high priority task
            
    
    return task_dict

task_manager(tasks)

defaultdict(dict,
            {'office': deque([36871, 40690, 33850]),
             'voltage': deque([41667, 35364])})

In [13]:
#How to create custom dict from list of tuples

user_list = [
    (1, 'Nick'), (2, 'Zack'), (3, 'Fuck'),
    (4, 'Rick'), (5, 'Thich'), (6, 'Chick'),
    (7, 'Inch'), (8, 'Finch'), (9, 'Grinch')
]

users = list()

for element in user_list:
    users.append({'id': element[0], 'name': element[1]})
users

[{'id': 1, 'name': 'Nick'},
 {'id': 2, 'name': 'Zack'},
 {'id': 3, 'name': 'Fuck'},
 {'id': 4, 'name': 'Rick'},
 {'id': 5, 'name': 'Thich'},
 {'id': 6, 'name': 'Chick'},
 {'id': 7, 'name': 'Inch'},
 {'id': 8, 'name': 'Finch'},
 {'id': 9, 'name': 'Grinch'}]

In [14]:
#Slices in array

def get_chess(a):
    zeros= np.zeros((a,a), dtype=int)
    zeros[1::2,::2]=1
    zeros[::2,1::2]=1
    return zeros
    
print(get_chess(6))

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [15]:
#Minimum and maximum distance between vectors

def min_max_dist(*vectors):
    distance = []
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            distance += [np.linalg.norm(vectors[i]-vectors[j])]       
    return min(distance), max(distance)
    
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])


print(min_max_dist(vec1, vec2, vec3))

(5.196152422706632, 10.392304845413264)


In [16]:
#Scalar product of vectors and finding perpendicular

def any_normal(*vectors):
    scalar_prod = []
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            scalar_prod += [np.dot(vectors[i],vectors[j])]       
    return 0 in scalar_prod


vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])

print(any_normal(vec1, vec2, vec3))

True


In [1]:
#Finding all combinations
import itertools
list_= [i for i in range(10)]
list_combinations = [i for i in itertools.combinations(list_, 3)]
list_combinations

[(0, 1, 2),
 (0, 1, 3),
 (0, 1, 4),
 (0, 1, 5),
 (0, 1, 6),
 (0, 1, 7),
 (0, 1, 8),
 (0, 1, 9),
 (0, 2, 3),
 (0, 2, 4),
 (0, 2, 5),
 (0, 2, 6),
 (0, 2, 7),
 (0, 2, 8),
 (0, 2, 9),
 (0, 3, 4),
 (0, 3, 5),
 (0, 3, 6),
 (0, 3, 7),
 (0, 3, 8),
 (0, 3, 9),
 (0, 4, 5),
 (0, 4, 6),
 (0, 4, 7),
 (0, 4, 8),
 (0, 4, 9),
 (0, 5, 6),
 (0, 5, 7),
 (0, 5, 8),
 (0, 5, 9),
 (0, 6, 7),
 (0, 6, 8),
 (0, 6, 9),
 (0, 7, 8),
 (0, 7, 9),
 (0, 8, 9),
 (1, 2, 3),
 (1, 2, 4),
 (1, 2, 5),
 (1, 2, 6),
 (1, 2, 7),
 (1, 2, 8),
 (1, 2, 9),
 (1, 3, 4),
 (1, 3, 5),
 (1, 3, 6),
 (1, 3, 7),
 (1, 3, 8),
 (1, 3, 9),
 (1, 4, 5),
 (1, 4, 6),
 (1, 4, 7),
 (1, 4, 8),
 (1, 4, 9),
 (1, 5, 6),
 (1, 5, 7),
 (1, 5, 8),
 (1, 5, 9),
 (1, 6, 7),
 (1, 6, 8),
 (1, 6, 9),
 (1, 7, 8),
 (1, 7, 9),
 (1, 8, 9),
 (2, 3, 4),
 (2, 3, 5),
 (2, 3, 6),
 (2, 3, 7),
 (2, 3, 8),
 (2, 3, 9),
 (2, 4, 5),
 (2, 4, 6),
 (2, 4, 7),
 (2, 4, 8),
 (2, 4, 9),
 (2, 5, 6),
 (2, 5, 7),
 (2, 5, 8),
 (2, 5, 9),
 (2, 6, 7),
 (2, 6, 8),
 (2, 6, 9),
 (2, 7, 8),
 (2,

---

#### Построение доверительного интервала

In [2]:
#При известном истинном стандартном отклонении
def confidence_interval_sigma(n, x_mean, sigma, gamma):
    """Function to evaluate confidence interval with known true standard deviation

    Args:
        n (int): sample size
        x_mean (int): sample mean
        sigma (int): true standard deviation
        gamma (float): reliability level 0-1

    Returns:
        float: lower_bound, upper_bound
    """
    alpha = 1 - gamma # уровень значимости

    z_crit = round(-norm.ppf(alpha/2),2) # z критическое

    eps = z_crit * sigma/(n ** 0.5) #погрешность
    lower_bound = round(x_mean - eps,2) # левая (нижняя) граница
    upper_bound = round(x_mean + eps,2) # правая (верхняя) граница
    confidence_interval = (lower_bound, upper_bound) # создаём кортеж из округлённых границ интервала
    print(f'Доверительный интервал: {lower_bound, upper_bound}, z-крит: {z_crit}') # выводим результат
    return lower_bound, upper_bound, z_crit

In [4]:
#При известном истинном стандартном отклонении
def confidence_interval():
    pass